refactor deploy workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -4,10 +4,11 @@ on:
   push:
     tags:
       - testflight/v[0-9]+.[0-9]+.[0-9]+-*.[0-9]+
+      - appstore/v[0-9]+.[0-9]+.[0-9]+-*.[0-9]+
 
 jobs:
   deploy:
-    name: Execute fastlane for testflight
+    name: Execute fastlane for testflight / appstore
     
     defaults:
       run:
@@ -30,7 +31,12 @@ jobs:
         id: regex
         with:
           text: ${{ github.ref_name }}
-          regex: '^testflight\/v(\d+)\.(\d+)\.(\d+)-(release|debug)\.(\d+)$'
+          regex: '^(testflight|appstore)\/v(\d+)\.(\d+)\.(\d+)-(release|debug)\.(\d+)$'
+      
+      - if: ${{ steps.regex.outputs.group1 == 'appstore' && steps.regex.outputs.group5 == 'debug' }}
+        run: |
+          echo "you can't upload debug build to appstore!"
+          exit 1
       
       - uses: actions/checkout@v3
 
@@ -40,8 +46,8 @@ jobs:
 
       - name: Set version number and build number
         run: |
-          echo "VERSION_NUMBER=${{ steps.regex.outputs.group1 }}.${{ steps.regex.outputs.group2 }}.${{ steps.regex.outputs.group3 }}" >> $GITHUB_ENV
-          echo "BUILD_NUMBER=${{ steps.regex.outputs.group5 }}" >> $GITHUB_ENV
+          echo "VERSION_NUMBER=${{ steps.regex.outputs.group2 }}.${{ steps.regex.outputs.group3 }}.${{ steps.regex.outputs.group4 }}" >> $GITHUB_ENV
+          echo "BUILD_NUMBER=${{ steps.regex.outputs.group6 }}" >> $GITHUB_ENV
 
       - name: Install Ruby Dependencies
         run: bundle install
@@ -53,22 +59,42 @@ jobs:
             ${{ secrets.MATCH_DEPLOY_KEY }}
           repo-mappings: |
             github.com/wafflestudio/wafflestudio-apple-certificates
+      
+      - name: Configure ssh agent
+        env:
+          MATCH_DEPLOY_KEY: ${{ secrets.MATCH_DEPLOY_KEY }}
+          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
+        run: |
+          eval "$(ssh-agent -s)"
+          ssh-add - <<< "${MATCH_DEPLOY_KEY}"
 
       - name: Upload dev app to testflight
-        if: ${{ steps.regex.outputs.group4 == 'debug' }}
+        if: ${{ steps.regex.outputs.group1 == 'testflight' && steps.regex.outputs.group5 == 'debug' }}
         env:
           DEBUG_CONFIG: ${{ secrets.DEBUG_CONFIG }}
           MATCH_DEPLOY_KEY: ${{ secrets.MATCH_DEPLOY_KEY }}
           GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
-          MATCH_READONLY: true
         run: |
-          eval "$(ssh-agent -s)"
-          ssh-add - <<< "${MATCH_DEPLOY_KEY}"
+          # eval "$(ssh-agent -s)"
+          # ssh-add - <<< "${MATCH_DEPLOY_KEY}"
           echo "$DEBUG_CONFIG" > SNUTT/DebugConfig.xcconfig
           bundle exec fastlane beta --env dev
 
       - name: Upload prod app to testflight
-        if: ${{ steps.regex.outputs.group4 == 'release' }}
+        if: ${{ steps.regex.outputs.group1 == 'testflight' && steps.regex.outputs.group5 == 'release' }}
+        env:
+          RELEASE_CONFIG: ${{ secrets.RELEASE_CONFIG }}
+          MATCH_DEPLOY_KEY: ${{ secrets.MATCH_DEPLOY_KEY }}
+          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
+        run: |
+          # eval "$(ssh-agent -s)"
+          # ssh-add - <<< "${MATCH_DEPLOY_KEY}"
+          echo "$RELEASE_CONFIG" > SNUTT/ReleaseConfig.xcconfig
+          echo "Not Implemented"
+          bundle exec fastlane beta --env prod
+      
+      - name: Upload prod app to App Store
+        if: ${{ steps.regex.outputs.group1 == 'appstore' && steps.regex.outputs.group4 == 'release' }}
         env:
           RELEASE_CONFIG: ${{ secrets.RELEASE_CONFIG }}
           MATCH_DEPLOY_KEY: ${{ secrets.MATCH_DEPLOY_KEY }}
@@ -79,5 +105,4 @@ jobs:
           ssh-add - <<< "${MATCH_DEPLOY_KEY}"
           echo "$RELEASE_CONFIG" > SNUTT/ReleaseConfig.xcconfig
           echo "Not Implemented"
-          bundle exec fastlane beta --env prod
-      
+          # bundle exec fastlane appstore --env prod
